### ISSUE TITLE
Error when calling timeseries object to view in console (Tutorial 3)

### ISSUE THREAD

**Issue by dlevenstein** [PeyracheLab/pynapple#11] opened 2021-11-16 21:19 UTC
During the tutorial (main3_tuningcurves.py, lines 37-38) we declare some spikes:
spikes = np.short(np.random.uniform(0,duration,100))
spikes = ap.Ts(spikes, time_units = 's')

Calling:
>>spikes

to view the spikes in the command line returns the following error:

  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 702, in __call__
    printer.pretty(obj)

  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/lib/pretty.py", line 394, in pretty
    return _repr_pprint(obj, self, cycle)

  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/lib/pretty.py", line 700, in _repr_pprint
    output = repr(obj)

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py", line 1301, in __repr__
    self.to_string(

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py", line 1360, in to_string
    formatter = fmt.SeriesFormatter(

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/io/formats/format.py", line 272, in __init__
    self._chk_truncate()

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/io/formats/format.py", line 294, in _chk_truncate
    series = concat((series.iloc[:row_num], series.iloc[-row_num:]))

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 298, in concat
    return op.get_result()

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 485, in get_result
    result = cons(res, index=self.new_axes[0], name=name, dtype=res.dtype)

  File "/Users/dl2820/Code Libraries/pynapple/pynapple/core/time_series.py", line 190, in __init__
    super().__init__(index=t, data=d, **kwargs)

TypeError: __init__() got multiple values for keyword argument 'index'

**Comment by dlevenstein** [comment] 2021-11-16 21:20
Maybe similar to Adrien's issue #10 ?

**Comment by dlevenstein** [comment] 2021-11-16 21:21
I get a similar error when calling the angle variable declared in line 34

angle = ap.Tsd(t = np.arange(0, duration, dt), d = angle, time_units = 's')

**Comment by gviejo** [comment] 2021-11-16 22:12
Yes it's the same error as in #10. One way to solve it is to try to install a previous version of pandas. Try
`conda install pandas=1.0.3`

**Comment by gviejo** [comment] 2021-11-16 22:12
I will solve it for the next release.
Duplicate of #10

**Comment by gviejo** [comment] 2021-11-16 22:27
Ok to be more precise you need python == 3.6 and pandas = 1.0.3. 
You can reinstall python within your environment with
`conda install python=3.6

**Comment by gviejo** [comment] 2021-12-08 00:10
Solved by overriding rep and str. @

**Closed by gviejo** 2021-12-08 00:10 UTC
